
-- filtros quantitativos

-- USADOS PARA FILTRAR DADOS QUANTITATIVOS (NUMEROS-DATA)
-- EM CASO DE TEXTOS É RESPEITADO A ORDEM ALFABETICA

-- > MAIOR QUE
-- < MENOR QUER
-- >= MAIOR IGUAL
-- <= MENOR IGUAL
-- <> DIFERENTE DE
-- BEETWEEN (PEGA UM RANGE XX A YY)

USE SUCO_VENDAS


SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE > 18


SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE < 18

SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE <> 18


-- DATAS
-- YYYY-MM-DD (ANO MES E DIA)

SELECT * FROM TABELA_DE_CLIENTES
WHERE DATA_DE_NASCIMENTO >= '1995-03-19'