
-- EXPRESSOES LOGICAS NOS RETORNAM UM VALOR BOOLEANO (TRUE E FALSE)
-- AND (TODAS AS CONDIÇÕES PRECISAM SER TRUE) 
-- OR (APENAS UMAS DAS CONDIÇÕES PRECISAM SER TRUE)
-- NOT (INVERTE A CONDIÇÃO APRESENTADA)


USE SUCO_VENDAS


-- Utilizando o and

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' and TAMANHO = '470 ml'


-- utilizando o or
SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'Manga' or TAMANHO = '470 ml')

-- in
-- melhora a sintaxe (evita multiplos or's)
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR  in ('Manga','Laranja','Melancia')


